import {
  AUFlag,
  BGFlag,
  BRFlag,
  CAFlag,
  CHFlag,
  CNFlag,
  CZFlag,
  DKFlag,
  EUFlag,
  GBFlag,
  HKFlag,
  HUFlag,
  IDFlag,
  ILFlag,
  INFlag,
  ISFlag,
  JPFlag,
  KRFlag,
  MXFlag,
  MYFlag,
  NOFlag,
  NZFlag,
  PHFlag,
  PLFlag,
  ROFlag,
  SEFlag,
  SGFlag,
  THFlag,
  TRFlag,
  USFlag,
  ZAFlag,
} from "@/components/flag";

export const CountryFlags = {
  AUD: <AUFlag />,
  BGN: <BGFlag />,
  BRL: <BRFlag />,
  CAD: <CAFlag />,
  CHF: <CHFlag />,
  CNY: <CNFlag />,
  CZK: <CZFlag />,
  DKK: <DKFlag />,
  EUR: <EUFlag />,
  GBP: <GBFlag />,
  HKD: <HKFlag />,
  HUF: <HUFlag />,
  IDR: <IDFlag />,
  ILS: <ILFlag />,
  INR: <INFlag />,
  ISK: <ISFlag />,
  JPY: <JPFlag />,
  KRW: <KRFlag />,
  MXN: <MXFlag />,
  MYR: <MYFlag />,
  NOK: <NOFlag />,
  NZD: <NZFlag />,
  PHP: <PHFlag />,
  PLN: <PLFlag />,
  RON: <ROFlag />,
  SEK: <SEFlag />,
  SGD: <SGFlag />,
  THB: <THFlag />,
  TRY: <TRFlag />,
  USD: <USFlag />,
  ZAR: <ZAFlag />,
} as const;
